write a python function to perform one-hot encoding of nominal values. The function should take in a 1D numpy array x of integer values and an optional integer n_col representing the number of columns for the one-hot encoded array. if n_col is not provided, it should be automatically determined from the input array.

In [ ]:
import numpy as np
def to_categorical(x,n_col=None):
  if not n_col:
    n_col=np.amax(x)+1
  #initialize a matrix of zeros with sahpe (number of samples, n_col)
  one_hot=np.zeros((x.shape[0],n_col))
  #set the appropriate elements to 1
  one_hot[np.arange(x.shape[0]),x]=1 #np.arange(x.shape[0]) is the row indices of one_hot matrix and x is the column indices/ np.arange(x.shape[0]):Generates an array of indices corresponding to the rows of the one_hot array.
  return one_hot


In [ ]:
x=np.array([0,1,2,1,0])
output=to_categorical(x)
print(output)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
